[package]
name = "kobink"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.18"
hyper = "0.14.27"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.68"
tokio = { version = "1.28", features = ["full"] }
tower = { version = "0.4.13", features = ["tokio", "tracing"] }
tower-http = { version = "0.4.1", features = ["tower", "tokio", "tracing", "trace"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
